### ISSUE TITLE
in functionality is buggy.

### ISSUE THREAD

**Issue by jperkelens** [didit-tech/FastLegS#37] opened 2012-10-12 15:45 UTC
Example:
{ 'field1.equals' : val, 'field2.in: [val2, val3] } will produce 'SELECT \* from table where field1 = $1 AND field2 IN ($1, $2, $3)

**Comment by backhand** [comment] 2013-01-29 20:47
I've uncovered this bug as well - a workaround is to place the in/nin predicate first, i.e. like this:
{ 'field2.in: [val2, val3], 'field1.equals' : val }

The bug is caused by the utils.quote function which doesn't take into account that previous outValues are "taken" by previous operators. By placing the in/nin predicate first, the outValues correspond to the values actually meant for that operator. This probably won't make sense unless you check the actual code - see statements.js:buildOperator and utils.js:quote :)

**Comment by thadclay** [comment] 2013-01-30 01:27
Fixed in #48

**Closed as completed** 2013-01-30 01:27 UTC
Labels: bug
